name: it-wars

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: itwars-app

    restart: unless-stopped

    ports:
      - "127.0.0.1:3000:3000"

    env_file:
      - .env

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}

    depends_on:
      - postgres

  postgres:
    image: postgres:17

    container_name: itwars-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - itwars_postgres_data:/var/lib/postgresql/data

volumes:
  itwars_postgres_data: